FROM node:10.12.0-alpine
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN npm install
WORKDIR /index
ENV NODE_ENV prod
COPY package.json ./index
RUN npm install --only=production
ARG port=80
EXPOSE $port
COPY . ./index
CMD ["npm", "start"]